# Generated by Django 4.2.11 on 2025-04-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appmuhasebe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onaydefterkayitmodel",
            name="olurTarih",
            field=models.DateField(auto_now_add=True),
        ),
    ]
