# Generated by Django 4.2.11 on 2025-04-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appmuhasebe", "0002_alter_onaydefterkayitmodel_olurtarih"),
    ]

    operations = [
        migrations.AddField(
            model_name="onaydefterkayitmodel",
            name="olurSGBBelgeNo",
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="onaydefterkayitmodel",
            name="olurTarih",
            field=models.DateField(),
        ),
    ]
