# Generated by Django 4.2.11 on 2025-05-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appmuhasebe", "0003_onaydefterkayitmodel_olursgbbelgeno_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onaydefterkayitmodel",
            name="olurAciklama",
            field=models.CharField(default="my_default_value", max_length=200),
        ),
    ]
