# Generated by Django 4.2.11 on 2025-05-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appmuhasebe", "0004_alter_onaydefterkayitmodel_oluraciklama"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onaydefterkayitmodel",
            name="olurAciklama",
            field=models.CharField(default="my_default_value", max_length=2500),
        ),
    ]
