# Generated by Django 4.2.11 on 2025-06-04 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appmuhasebe", "0005_alter_onaydefterkayitmodel_oluraciklama"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZiraatDefterKayitModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ziraatNo", models.CharField(max_length=4)),
                ("ziraatTarih", models.DateField()),
                ("ziraatFirmaIlgili", models.CharField(max_length=100)),
                (
                    "ziraatAciklama",
                    models.CharField(default="my_default_value", max_length=2500),
                ),
                ("ziraatSGBBelgeNo", models.CharField(max_length=10)),
                ("ziraatFaturaTarih", models.DateField()),
                ("ziraatFaturaNo", models.CharField(max_length=100)),
                ("ziraatOdemeTutar", models.CharField(max_length=20)),
                ("ziraatParaBirimi", models.CharField(max_length=20)),
                (
                    "username",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
